StartupEvents.registry('item', event =>{
	event.create('basic_mechanism').displayName('Basic mechanism')
	event.create('incomplete_basic_mechanism').displayName('Incomplete basic mechanism')
	event.create('copper_mechanism').displayName('Copper mechanism')
	event.create('incomplete_copper_mechanism').displayName('Incomplete copper mechanism')
	event.create('steel_mechanism').displayName('Steel mechanism')
	event.create('incomplete_steel_mechanism').displayName('Incomplete steel mechanism')
	event.create('enchanted_mechanism').displayName('Enchanted mechanism')
	event.create('incomplete_enchanted_mechanism').displayName('Incomplete enchanted mechanism')
	event.create('conductive_mechanism').displayName('Conductive mechanism')
	event.create('incomplete_conductive_mechanism').displayName('Incomplete conductive mechanism')
	event.create('mystical_mechanism').displayName('Mystical mechanism')
	event.create('incomplete_mystical_mechanism').displayName('Incomplete mystical mechanism')
	event.create('simulated_base').displayName('Simulated base')
	event.create('simulated_mechanism').displayName('Simulated mechanism')
	event.create('incomplete_basic_control_circuit').displayName('Incomplete control circuit')
	event.create('mek_mechanism').displayName('Mek mechanism')
	event.create('mek_base').displayName('Mek base')
	event.create('superseed').displayName('Super semilla')
})

