StartupEvents.registry('item', event =>{
	event.create('alma').displayName('Alma de dragon')
	event.create('antimateria').displayName('Antimateria')
	event.create('blackhole').displayName('BlackHole')
	event.create('brujulamaldita').displayName('Brujula maldita')
	event.create('calavera').displayName('Calavera')
	event.create('catalizadordeoblivion').displayName('Catalizador de Oblivion')
	event.create('combustible').displayName('Combustible')
	event.create('doll').displayName('Muneco de paja')
	event.create('easteregg').displayName('Easter egg')
	event.create('emeraldcoin').displayName('Moneda de esmeralda')
	event.create('ironcoin').displayName('Moneda de hierro')
	event.create('lingotedeacero').displayName('Lingote de acero')
	event.create('miniportal').displayName('Mini portal')
	event.create('minireactor').displayName('Mini reactor')
	event.create('moneda_de_oro').displayName('Moneda de oro')
	event.create('netheritecoin').displayName('Moneda de netherite')
	event.create('patricio').displayName('Patricio')
	event.create('planos').displayName('Planos')
	event.create('semilla').displayName('Semilla')
	event.create('star').displayName('Mega estrella')
	event.create('starnugget').displayName('Fragmentos de mega estrella')
	event.create('transmisor').displayName('Transmisor')
})